services:
  nginx:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: host
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
      - NGINX_PORT=${NGINX_PORT}
    image: nginx:latest
    labels:
      createdBy: "Apps"