services:
  rustfs:
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:9000"
    volumes:
      - ./data:/data
    user: root
    environment:
      - TZ=Asia/Shanghai
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_LOG_LEVEL=info
      - RUSTFS_ADDRESS=0.0.0.0:9000
      # - RUSTFS_SERVER_DOMAINS=example.com
      # - RUSTFS_ACCESS_KEY=rustfsadmin
      # - RUSTFS_SECRET_KEY=rustfsadmin
    image: rustfs/rustfs:dev-production
    labels:
      createdBy: "Apps"