services:
  zitadel:
    image: 'ghcr.io/zitadel/zitadel:latest'
    container_name: zitadel
    restart: 'always'
    networks:
      - 1panel-network
    command: 'start-from-init --masterkey "${PANEL_MASTER_KEY}" --tlsMode external'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: ${ZITADEL_DATABASE_POSTGRES_HOST}
      ZITADEL_DATABASE_POSTGRES_PORT: ${ZITADEL_DATABASE_POSTGRES_PORT}
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${ZITADEL_DATABASE_POSTGRES_DATABASE}
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${ZITADEL_DATABASE_POSTGRES_USER_USERNAME}
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${ZITADEL_DATABASE_POSTGRES_USER_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: true
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME: Admin
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME: zitadel-admin-sa
      ZITADEL_FIRSTINSTANCE_ORG_MACHINE_PAT_SCOPES: openid
      ZITADEL_FIRSTINSTANCE_PATPATH: /machinekey/zitadel-admin-sa.token
      ZITADEL_LOG_LEVEL: debug
      ZITADEL_MASTERKEY: ${ZITADEL_MASTERKEY}
      ZITADEL_TLS_ENABLED: "false"
      ZITADEL_EXTERNALPORT: ${ZITADEL_EXTERNALPORT:-443}
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_EXTERNALDOMAIN:-auth.sction.com}
    ports:
      - "${PANEL_APP_PORT_HTTP}:8080/tcp"
    labels:
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
