services:
  fnss:
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:9000"
    # network_mode: host
    volumes:
      - ./config:/fast-note-sync/config
      - ./data:/fast-note-sync/data
    environment:
      - TZ=Asia/Shanghai
    image: haierkeys/fast-note-sync-service:latest
    labels:
      createdBy: "Apps"