services:
  newsnow:
    image: ghcr.io/ourongxing/newsnow:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "${PANEL_APP_PORT_HTTP}:4444"
    volumes:
      - .data:/usr/app/.data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=1100757
      - G_CLIENT_SECRET=Iv23lixo906t41lxERKu
      - JWT_SECRET=
      - INIT_TABLE=false
      - ENABLE_CACHE=true
      # - MYSQL_HOST=172.17.0.1
      # - MYSQL_PORT=3306
      # - MYSQL_USER=newsnow
      # - MYSQL_PASSWORD=EGrYTKdynehZ6Kwa
      # - MYSQL_DATABASE=newsnow
      # - MYSQL_SSL=false
    labels:
      createdBy: "Apps"